### ISSUE TITLE
OIDC authentication question

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-python-driver#107]
I have a simple question regarding user authentication and authorisation with OIDC token.
Based on this implementation:
https://github.com/Open-EO/openeo-python-driver/blob/160579d289869baf0ffe143d98b84b1919a199bc/openeo_driver/users/auth.py#L205-L207
does this mean a user with e.g. EGI check-in account, who is _not_ in a openEO group, but obtains a token with some other - unrelated - client, will be able to use that token to access resources? On the first glance it seems like this just checks if the token is valid. 
Of course e.g. EGI returns non-standard fields that contain user roles etc. that could be checked against.
I don't properly understand this, so I'd be thankful for the help.

**Comment by soxofaan** [comment]
Indeed, at the level of the openeo-python-driver (which acts a library for actual back-end implementations like openeo-geopyspark-driver and openeo-aggregator), there is not really concrete user validation.

The user verification used in  openEO Platform (based on an EGI virtual organisation structure) is implemented here:
https://github.com/Open-EO/openeo-aggregator/blob/master/src/openeo_aggregator/backend.py#L698-L737
and called from 
https://github.com/Open-EO/openeo-python-driver/blob/160579d289869baf0ffe143d98b84b1919a199bc/openeo_driver/users/auth.py#L78-L80

**Comment by Ardweaden** [comment]
Thanks a lot, this makes a lot of sense!

So on the level of the backend, should we create an EGI client inside the openEOP group? I'm not quite sure why that would be necessary, apart from maybe more control who we add etc. ? The aggregator should be able to make requests to the backend with the provided token, as we'll be checking the same values for roles/permissions etc. as the aggregator. This means, however, that we shouldn't be checking for some roles/permissions specific to the backend.

Is this understanding correct? I appreciate you're taking your time to explain this.

**Comment by soxofaan** [comment]
>  should we create an EGI client inside the openEOP group?

No, EGI OIDC clients (also referred to as [service provider](https://docs.egi.eu/providers/check-in/sp/#openid-connect-service-provider)  in EGI docs) and openEO Platform user groups have no relevant relation in this regard: 
group membership is defined on the user directly, regardless of OIDC client in play.

The only consideration I can think of is that the OIDC client is set up to include the `eduperson_entitlement` scope (at least), so that the user_info lookup done at the back-end side returns group membership information.


> ... as we'll be checking the same values for roles/permissions etc. as the aggregator.  This means, however, that we shouldn't be checking for some roles/permissions specific to the backend.

I don't understand what you mean here

**Comment by soxofaan** [comment]
(sorry for delayed answer)

>  I still don't quite get why a backend would have to specify its own client though. E.g., if I understand correctly every backend could just return the ones VITO uses and everything should just work?

That would indeed work, but it would be misleading to the user: at some point in the authentication flow the user has to grant user info access to the client owner (VITO in this example), while in reality another backend would actually get access to that user data.

For the aggregator for example we use a different client than the VITO one, so that we can be more honest that more parties get access to user info

> So I assume the aggregator relays the same request (using the same access token) to some backend? 

no, the aggregator does not relay to another backend, it makes direct request to the EGI userinfo endpoint.

> In that case the checks in aggregator and backend have to be the same. For example, Sentinel Hub backend shouldn't be checking if a user is in vo.sentinelhub.openeo group etc.

I think it's better that each back-end does its own checks. And indeed, there would be quite some duplication here. 
But the problem is that back-ends can be accessed directly without the aggregator in between and a back-end can not reliably tell the difference (there are no private communication channels, it's all just plain HTTPS requests).
