### ISSUE TITLE
correctness of area_in_square_meters

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#144]
While working on the failing integration tests due to #141 I was covering my changes with tests and have a question about current area_in_square_meters implementation:
https://github.com/Open-EO/openeo-python-driver/blob/dad6bc97846cfbcd5b32bd97de5cf147a8b3522f/openeo_driver/util/utm.py#L74-L91

I added a test in dad6bc97846cfbcd5b32bd97de5cf147a8b3522f  where I use a GeoJSON with a square with side 2.3km (based on length of Watersportbaan Gent): area is around (2.3 km)^2  = 5.29 km^2, but current implementation of area_in_square_meters gives a result around 8 km^2, which is quite a difference:
https://github.com/Open-EO/openeo-python-driver/blob/dad6bc97846cfbcd5b32bd97de5cf147a8b3522f/tests/test_vectorcube.py#L260-L267

**Comment by Pratichhya** [comment]
I was testing a service for 1 hectare area whose area changes in a different manner(decreases in area, i.e. 2875sq.m). Similar was the case when tested for 100 hectares.
job id: 'j-b8ec79678ef34937bef08c3ef1404187'

**Comment by Pratichhya** [comment]
I retried testing service for a specific area, yet it seems different than expected. E.g.: when tested for a 1ha polygon, it's area was changed to 13089.722 sq_m instead of 10000 sq_m (job id: j-8d087ab0f16a47c18bc4198efb52290c), similarly for a polygon on 10ha area was 550590.284 sq_m (job id: j-6a0ee095fc71415a9fb5b44856c17293).

**Comment by JeroenVerstraelen** [comment]
Hello, @Pratichhya. Can you share the code and polygons you used? I'll check it as soon as I can.

**Comment by JeroenVerstraelen** [comment]
@Pratichhya, I have tested the new area_in_square_meters function with your 1ha polygon, and it returned a value of 10,155.584 m². This result is identical to what we get on QGIS.

The issue stems from the way we handle aggregate_spatial in the dry_run. In that section, we use the bounding box (bbox) of the provided polygon as our filter:
https://github.com/Open-EO/openeo-python-driver/blob/master/openeo_driver/dry_run.py#L503
This bbox is later utilized to compute the area, which is then recorded in the job_metadata.json file:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/deploy/batch_job.py#L97

The difference is quite evident in QGIS:
<img src="https://user-images.githubusercontent.com/3028262/227189566-8e5c0696-d007-4965-8f94-9527ebaa4e5a.png" alt="Screenshot from 2023-03-23 12-25-22" width="400" height="300">

The bbox has an area of approximately 20,000 m². However, considering the extra vector_buffer in your Anomaly_Detection UDP, this likely results in the 13,089.722 m² value that you observe for your batch job.

@soxofaan @jdries, is it intentional that we use the bbox of the provided polygons for our area calculation in job_metadata.json?

**Comment by jdries** [comment]
For weak_spatial_extent we probably want the bounding box, but in batch job metadata, polygons should be used to calculate area if available because openEO processing is normally smart enough to work on the polygons only.
