### ISSUE TITLE
Missing return schema on `load_disk_data`

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-python-driver#44]
Hi,

i was just connecting to the VITO 1.0.0 back-end with the R-client and had a problem parsing the function `load_disk_data`. I am not sure if the API allows to specify a return parameter without a schema representation. Is this intended or is the schema part just missing?

**Comment by m-mohr** [comment]
Hi @flahn,

as we were discussing this recently, I need to clarify this.

The process correctly defined the "returns" as follows:

```json
"returns": {
  "description": "the data as a data cube",
  "schema": {}
}
```

An empty schema is not `void` (as you likely thought), but means any data type in json schema. Thus the schema is valid and can basically return anything. So that seems like a client issue.

**Comment by flahn** [comment]
OK that solves it, I will adapt accordingly
