### ISSUE TITLE
misleading spatial extent of Terrascope imagery

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-python-driver#57]
I found that the stated extent of the Terrascope imagery is misleading. For all datasets it gives the usual Sentinel1/2 global coverage, while the actual availability for both S1/2 is much smaller and more or less bound to europe (checking with viewer.terrascope.be). I think it would increase usability when this could be communicated.

**Comment by soxofaan** [comment]
@jdries   we probably can query a more honest spatial extent from oscars?

**Comment by jdries** [comment]
We actually communicate this in the description itself, and provide the WMTS and viewer links so users can inspect visually.
Next to that, we're also working out a mechanism to have a SENTINEL2_L2A layer that automatically falls back to Sentinelhub where the data is not available.

For Sentinel-2: Europe has quite a few overseas areas that we process, and we have data from china to south america, so it is actually global. I'm not sure if we have a fast way to create the union of all these bounds using oscars.
For Sentinel-1 the situation is similar, but it's much less data.

In any case, I agree that this geometry is not the most useful field, but don't have easy solutions other than what we already do, so closing this one.

**Comment by m-mohr** [comment]
Please be aware that you can fine-tune the extents by providing multiple spatial extents for a collection so that oversea areas etc are not so problematic. STAC allows that: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object

> The first bounding box always describes the overall spatial extent of the data. All subsequent bounding boxes can be used to provide a more precise description of the extent and identify clusters of data. 

Not sure whether your underlying data store allows to pull such information, but at least I want to make you aware of this option.
