### ISSUE TITLE
OIDC default clients: add redirect urls and grant types

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#65]
The Web Editor would also like to use the simplified OIDC workflow, but instead of just a client id, it would need the grants and redirect URLs to be listed. Could that be implemented to fully align with PR https://github.com/Open-EO/openeo-api/pull/366?

**Comment by soxofaan** [comment]
support for that was already added earlier this month: 12466e8b0bdf

got deployed this week in production, e.g. see https://openeo.vito.be/openeo/1.0/credentials/oidc

authorization code grant is however not listed because I have no idea what redirect url I should list however

**Comment by soxofaan** [comment]
> The Web Editor would also like to use the simplified OIDC workflow

why would you need the default client for the web editor? 
The web editor seems like the main use case where you can define your own OIDC client and would not need a back-end controlled default client. Especially now that we are converging to use EGI Check-in as OIDC provider.

**Comment by m-mohr** [comment]
I don't want to hardcode client Id's for all 10 or so back-ends out there.

**Comment by soxofaan** [comment]
> I don't want to hardcode client Id's for all 10 or so back-ends out there.

but then all 10 back-ends are required to hardcode the web editor redirect url :stuck_out_tongue:

**Comment by m-mohr** [comment]
They just need to print out all their allowed redirect URLs, in thr best case retrieved automatically from some kind of central config or API of the IP. You could have also hard coded them in the Python client.

**Comment by m-mohr** [comment]
By the way, the web editor can't connect via EGI Checkin to Platform. The redirect URL seems to be missing in the IP config.

**Comment by soxofaan** [comment]
> but then all 10 back-ends are required to hardcode the web editor redirect url

Sorry, I was probably thrown back here in an outdated mindset about how OIDC fits the openEO components. With the latest OIDC changes it does indeed make more sense to exploit the default OIDC clients of the backend more. The default clients feature I pushed for was originally to make the OIDC experience smoother for scripting (Python) use cases, while the web editor use case seemed already covered out of the box by OIDC. I didn't realize that the "default clients" is also turns out to be useful for the web editor.

On the other hand, it still looks a bit weird that a back-end has to cover client side OIDC implementation details  like redirect URLs. 
For now, it's just the web editor and the R client, which is feasible to manage at this point, but I wonder how this will scale if more (web) applications are going to pop up. Maybe the web editor or JS client should also support the device code flow (which does not require redirect urls)?


> Also, VITO + EODC don't grant us access to their Keycloak, so how should others configure their own client IDs anyway?

We both are starting to use and promote EGI Check-in instead of keycloak, which allows a user to register their own client. In principle at least, because the procedure to do that is quite challenging.

**Comment by m-mohr** [comment]
> For now, it's just the web editor and the R client,

The R client should likely migrate to Device Code, too, but until now there's no funding for it and no library to use. So will be a bit of effort. Maybe that changes in the next months.

> Maybe the web editor or JS client should also support the device code flow (which does not require redirect urls)?

Why bother a user with copy/pasting a device code if there's a flow that makes it work just by an automated redirect? Also, there's no JS library supporting the device code grant, so it's out of scope to implement it due to limited time/funding.

With the default client IDs we'll likely just cover our general-purpose/centrally hosted clients and make them as user-friendly as possible. Other web applications then need to register with EGI indeed.

> On the other hand, it still looks a bit weird that a back-end has to cover client side OIDC implementation details like redirect URLs.

You could argue the same for the Python client. *Client* IDs are obviously also client-side OIDC implementation details. But we want a smooth user experience, so that seems to be the way to go for now.

**Comment by soxofaan** [comment]
> You could argue the same for the Python client. Client IDs are obviously also client-side OIDC implementation details. 

I somewhat disagree. The OIDC client id is not an implementation detail, it is a reference to the entity that the end user has to trust and grant access to so that the backend can obtain user info. As such, it makes sense that it is part of the communication between the openEO backend and openEO client. 
The redirect URL is an implementation aspect chosen by a openEO client  (web) app, that only the OIDC identity provider has to be aware of, the openEO backend is not involved in any way in here (forwarding, requesting, nor serving this URL).

I'm not saying that the `redirect_urls` field is wrong, it just looks conceptually a bit out of place. But maybe it's just a matter of documenting that `redirect_urls` is not a whitelist chosen autonomously by the backend, but instead some kind of  compilation of urls that are chosen by other parties (R client, web editor, ...).

**Comment by m-mohr** [comment]
> I'm not saying that the `redirect_urls` field is wrong, it just looks conceptually a bit out of place. But maybe it's just a matter of documenting that `redirect_urls` is not a whitelist chosen autonomously by the backend, but instead some kind of compilation of urls that are chosen by other parties (R client, web editor, ...).

Happy to accept PRs! :-)

**Comment by m-mohr** [comment]
There's no a way to hardcode OIDC client IDs into the Web Editor config for a specific deployment, so you'd be able to login to the Platform from a specific Platform Web Editor deployment. But to make the services also work with the general deployment at editor.openeo.org, I'd suggest making the aggregator expose also redirect_urls and the authorization code grant type in the VITO / Aggregator config. @soxofaan Is there a plan to enable this?

**Comment by m-mohr** [comment]
Redirect URLs would be 
- https://editor.openeo.cloud
- https://editor.openeo.org

**Comment by soxofaan** [comment]
>  to make the services also work with the general deployment at editor.openeo.org, I'd suggest making the aggregator expose also redirect_urls and the authorization code grant type in the VITO / Aggregator config so that there's a single place where this is getting managed. @soxofaan Is there a plan to enable this?

FYI: the aggregator does not hardcode OIDC settings, but takes the intersection of the OIDC settings (based on issuer url) from the back-ends it is "proxying". For the default clients it uses the ones defined by the "primary" back-end, which is the VITO one at the moment.
So it is just a matter of configuring the default client of the VITO back-end.

Unfortunately, the intersection is currently only EGI dev (https://aai-dev.egi.eu/oidc/) because EODC dev instance does not list EGI production yet. And additionally, the self service UI of  EGI dev is broken (maybe just for me, I'm not sure yet), so I can not set these redirect URLs at the moment

**Comment by m-mohr** [comment]
> FYI: the aggregator does not hardcode OIDC settings, but takes the intersection of the OIDC settings (based on issuer url) from the back-ends it is "proxying". For the default clients it uses the ones defined by the "primary" back-end, which is the VITO one at the moment.
> So it is just a matter of configuring the default client of the VITO back-end.

Good to know.

> Unfortunately, the intersection is currently only EGI dev (https://aai-dev.egi.eu/oidc/) because EODC dev instance does not list EGI production yet.

I've tried to use my own hardcoded client ID now, but I'm getting "Bad client credentials". What do I miss?

> And additionally, the self service UI of EGI dev is broken (maybe just for me, I'm not sure yet), so I can not set these redirect URLs at the moment

Hmm, it works for me. I added new redirect URIs some minutes ago (Chrome on Win).

**Comment by soxofaan** [comment]
I just added `http://localhost:1410/`  as redirect URI to OIDC service config in EGI federation registry, now waiting for it to be approved

**Comment by m-mohr** [comment]
👍 Was `https://editor.openeo.org` already included?

**Comment by soxofaan** [comment]
>  Was https://editor.openeo.org already included?

indeed

**Comment by soxofaan** [comment]
also added "authorization_code+pkce"  grant for default client in VITO backend (still to be deployed at the moment)

**Comment by soxofaan** [comment]
will close this for now (it's just a matter of waiting for things to be deployed/approved)

**Comment by m-mohr** [comment]
Hmm, afaik the code doesn't reflect the redirect URLs though. So the Web Editor still won't work for VITO.

**Comment by soxofaan** [comment]
yeah, I always forget this "redirect_urls" field. Thanks for catching this

**Comment by soxofaan** [comment]
> I just added http://localhost:1410/ as redirect URI to OIDC service config in EGI federation registry, now waiting for it to be approved

I think it is approved now (I got email), but I can't double check because federation registry doesn't let me log in anymore  :man_shrugging:
